export { registerStudentSchema } from "./student";
export type { RegisterStudentInput } from "./student";
export { loginSchema, changePasswordSchema } from "./auth";
export type { LoginInput, ChangePasswordInput } from "./auth";
export { createSubjectSchema, createSubjectsFromCatalogSchema } from "./subjects";
export type { CreateSubjectInput, CreateSubjectsFromCatalogInput } from "./subjects";
export { updateRecordSchema } from "./attendance";
export type { UpdateAttendanceInput } from "./attendance";
export { createClassSchema, deleteClassSchema } from "./classes";
export type { CreateClassInput } from "./classes";
